apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mailpouch-staging-ip
    networking.gke.io/managed-certificates: mailpouch
    kubernetes.io/ingress.class: "gce"
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  defaultBackend:
    service:
      name: load-balancer
      port:
        number: 80
