apiVersion: batch/v1
kind: Job
metadata:
  generateName: db-migrate-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: staging-env
        - secretRef:
            name: rails-secrets-staging
            key: rails_master_key
        image: us-central1-docker.pkg.dev/mailpouch-364912/mailpouch/mailpouch-gke:latest

