apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: staging-env
        env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-secrets-staging
                key: rails_master_key
        image: us-central1-docker.pkg.dev/mailpouch-364912/mailpouch/mailpouch-gke:latest
        name: main
