apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-env
data:
  PIPE_ENV: staging
  RAILS_ENV: production
  RACK_ENV: production
  RAILS_LOG_TO_STDOUT: enabled
  RAILS_SERVE_STATIC_FILES: enabled
