apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpouch-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpouch-web
  template:
    metadata:
      labels:
        app: mailpouch-web
    spec:
      containers:
      - name: main
        image: us-central1-docker.pkg.dev/mailpouch-364912/mailpouch/mailpouch-gke:latest
        envFrom:
        - configMapRef:
            name: env
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-master-key
                key: rails_master_key
