# fly.toml file generated for mailpouch on 2023-03-03T17:39:39-03:00

app = "mailpouch"
primary_region = "dfw"
console_command = "/rails/bin/rails console"

[env]

[build]

[deploy]
  release_command = "./bin/rails db:prepare"

[processes]
  app = "./bin/rails s"
  sidekiq = "bundle exec sidekiq -C config/sidekiq.yml"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
