default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mailpouch_development

test:
  <<: *default
  database: mailpouch_test

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:database, :url) %>
